
const PLACES=[
 ['เมืองร้อยเอ็ด','บึงพลาญชัย','หัวใจกลางเมืองร้อยเอ็ด'],['ธวัชบุรี','พระธาตุอุปมุง','ศิลปะและศรัทธาแห่งลุ่มน้ำชี'],['เสลภูมิ','ลำน้ำยัง','วิถีชีวิตริมสายน้ำ'],['โพนทอง','กู่กาสิงห์จำลอง','ประตูสู่ร้อยเอ็ดตอนเหนือ'],['สุวรรณภูมิ','กู่พระโกนา','โบราณสถานศิลปะขอม'],['พนมไพร','บุญบั้งไฟ','ประเพณีขอฝนแห่งอีสาน'],['อาจสามารถ','ทุ่งกุลาร้องไห้','แหล่งข้าวหอมมะลิชั้นดี'],['เกษตรวิสัย','ข้าวหอมมะลิ','ของดีทุ่งกุลาร้องไห้'],['ปทุมรัตต์','ผ้าไหมสาเกต','ภูมิปัญญาทอผ้าท้องถิ่น'],['จตุรพักตรพิมาน','กู่คันธนาม','ร่องรอยอารยธรรมโบราณ'],['ธวัชบุรี','ธุงอีสาน','งานหัตถกรรมแห่งศรัทธา'],['เชียงขวัญ','ลำน้ำชี','เกษตรกรรมบนดินอุดม'],['ทุ่งเขาหลวง','เกลือสินเธาว์','ทรัพยากรจากผืนดิน'],['เมยวดี','ภูเขียว','ธรรมชาติร่มรื่นแดนอีสาน'],['โพธิ์ชัย','ผ้าไหม','ลวดลายจากภูมิปัญญา'],['โพนทราย','ทุ่งกุลา','ทุ่งกว้างกับเรื่องเล่ายาวนาน'],['เมืองสรวง','หอโหวด 101','แลนด์มาร์กสูงเด่นกลางเมือง'],['ศรีสมเด็จ','เกษตรพอเพียง','ชุมชนแข็งแรงอย่างยั่งยืน'],['หนองพอก','ผาน้ำย้อย','พระมหาเจดีย์ชัยมงคล'],['จังหาร','แม่น้ำชี','เส้นชัยแห่งมิตรภาพ']
];
const QUESTIONS=[
 ['สถานที่ใดเป็นหัวใจกลางเมืองร้อยเอ็ด?',['บึงพลาญชัย','ดอยสุเทพ','ทะเลบัวแดง'],0],['จังหวัดร้อยเอ็ดอยู่ในภาคใด?',['ภาคใต้','ภาคตะวันออกเฉียงเหนือ','ภาคตะวันตก'],1],['ข้าวขึ้นชื่อของทุ่งกุลาร้องไห้คือ?',['ข้าวหอมมะลิ','ข้าวบาร์เลย์','ข้าวญี่ปุ่น'],0],['หอโหวด 101 ได้แรงบันดาลใจจากอะไร?',['เครื่องดนตรีอีสาน','เรือหางยาว','ต้นตาล'],0],['พระมหาเจดีย์ชัยมงคลอยู่ที่อำเภอใด?',['หนองพอก','เมืองเชียงใหม่','บางละมุง'],0]
];
const KEY='lohd-run-101-v2';
const fresh=()=>({unlocked:1,levels:{},coins:0,best:0,name:'นักวิ่งสาเกต',scores:[]});
let save=load(),active=0,raf=0,state=null,last=0;
function load(){try{return {...fresh(),...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return fresh()}}
function persist(){localStorage.setItem(KEY,JSON.stringify(save));syncCloud()}
function toast(t){const e=document.querySelector('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
const $=s=>document.querySelector(s);
function show(id){cancelAnimationFrame(raf);document.querySelectorAll('main>section').forEach(x=>x.classList.toggle('hidden',x.id!==id));if(id==='stages')renderStages();if(id==='passport')renderPassport();if(id==='leaderboard')renderBoard();switchMusic(id==='gameScreen'?'game':'menu');updateHome()}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>show(b.dataset.view));
function updateHome(){const stars=Object.values(save.levels).reduce((n,x)=>n+(x.stars||0),0);$('#homeStars').textContent=`${stars}/60`;$('#homeCoins').textContent=save.coins;$('#homeStamps').textContent=`${Object.keys(save.levels).length}/20`;$('#continueBtn').textContent=save.unlocked>1?'วิ่งต่อ ▶':'เริ่มวิ่งเลย ▶'}
function renderStages(){const g=$('#stageGrid');g.innerHTML='';PLACES.forEach((p,i)=>{const d=save.levels[i],b=document.createElement('button');b.className='stage '+(d?'done':'');b.disabled=i+1>save.unlocked;b.innerHTML=`<span class="no">DISCOVERY ${String(i+1).padStart(2,'0')}</span><h3>${p[0]} • ${p[1]}</h3><div class="muted">${p[2]}</div><div class="stars">${d?'★'.repeat(d.stars)+'☆'.repeat(3-d.stars):b.disabled?'🔒':'☆☆☆'}</div>`;b.onclick=()=>start(i);g.append(b)})}
function renderPassport(){const g=$('#passportGrid');g.innerHTML='';PLACES.forEach((p,i)=>{const d=document.createElement('div');d.className='stamp '+(save.levels[i]?'got':'');d.innerHTML=save.levels[i]?`<div>✓<br><b>${p[0]}</b><br><small>${p[1]}</small></div>`:`<div>?</div>`;g.append(d)});$('#passportCount').textContent=`${Object.keys(save.levels).length} / 20 ตรา`}
function renderBoard(){let rows=[...save.scores].sort((a,b)=>b.score-a.score).slice(0,10);if(!rows.length)rows=[{name:'รอฮีโร่คนแรก',score:0,level:1}];$('#playerName').value=save.name;$('#scoreRows').innerHTML=rows.map((r,i)=>`<tr><td>${i+1}</td><td>${esc(r.name)}</td><td>${r.score.toLocaleString()}</td><td>${r.level}</td></tr>`).join('')}
function esc(s){const d=document.createElement('div');d.textContent=s;return d.innerHTML}
$('#saveName').onclick=()=>{save.name=$('#playerName').value.trim()||'นักวิ่งสาเกต';persist();toast('บันทึกชื่อแล้ว')};$('#continueBtn').onclick=()=>start(Math.min(save.unlocked-1,19));
const canvas=$('#game'),ctx=canvas.getContext('2d');
const runFrames=Array.from({length:13},(_,i)=>{const img=new Image();img.src=`assets/character/run/row2_frame${String(i+1).padStart(2,'0')}.png`;return img});
const jumpFrames=Array.from({length:5},(_,i)=>{const img=new Image();img.src=`assets/character/jump/jump_0${i+1}.png`;return img});
const slideFrames=['02','03'].map(n=>{const img=new Image();img.src=`assets/character/slide/slide_${n}.png`;return img});
const coinImage=new Image();coinImage.src='assets/coin/coin-101.png';
const fieldBackground=new Image();fieldBackground.src='assets/backgrounds/roi-et-rice-fields.png';
const audio={muted:false,current:'',menu:new Audio('assets/audio/music-menu.mp3'),game:new Audio('assets/audio/music-game.mp3'),coin:new Audio('assets/audio/coin-pickup.wav'),power:new Audio('assets/audio/power-pickup.mp3'),hit:new Audio('assets/audio/player-hit.mp3')};
audio.menu.loop=audio.game.loop=true;audio.menu.volume=.22;audio.game.volume=.28;audio.coin.volume=.42;audio.power.volume=.48;audio.hit.volume=.52;
Object.values(audio).filter(x=>x instanceof Audio).forEach(x=>x.preload='auto');
function switchMusic(name){if(audio.current===name&&!audio[name].paused)return;['menu','game'].forEach(k=>{if(k!==name){audio[k].pause();audio[k].currentTime=0}});audio.current=name;if(!audio.muted)audio[name].play().catch(()=>{})}
function playSfx(name){if(audio.muted)return;try{const s=audio[name].cloneNode();s.volume=audio[name].volume;s.play().catch(()=>{})}catch{}}
function playCoinSound(){playSfx('coin')}
let soundContext;function tone(from,to,duration=.12,volume=.045,type='sine'){if(audio.muted)return;try{soundContext??=new (window.AudioContext||window.webkitAudioContext)();const o=soundContext.createOscillator(),gain=soundContext.createGain(),now=soundContext.currentTime;o.type=type;o.frequency.setValueAtTime(from,now);o.frequency.exponentialRampToValueAtTime(to,now+duration);gain.gain.setValueAtTime(volume,now);gain.gain.exponentialRampToValueAtTime(.001,now+duration);o.connect(gain).connect(soundContext.destination);o.start(now);o.stop(now+duration)}catch{}}
$('#soundBtn').onclick=()=>{audio.muted=!audio.muted;$('#soundBtn').textContent=audio.muted?'🔇':'🔊';if(audio.muted){audio.menu.pause();audio.game.pause()}else switchMusic(audio.current||'menu');toast(audio.muted?'ปิดเสียงแล้ว':'เปิดเสียงแล้ว')};
addEventListener('pointerdown',()=>{if(!audio.muted&&audio.current)audio[audio.current].play().catch(()=>{})},{once:true});
function size(){const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);canvas.width=r.width*d;canvas.height=r.height*d;ctx.setTransform(d,0,0,d,0,0)}addEventListener('resize',size);
function start(level){hideOverlay();active=level;show('gameScreen');size();state={running:true,paused:false,t:0,distance:0,target:1450+level*70,speed:310+level*5,score:0,coins:0,lives:3,energy:0,power:0,inv:0,spawn:0,player:{x:110,y:0,vy:0,slide:false,jumpCount:0},items:[],particles:[]};updateHud();last=performance.now();raf=requestAnimationFrame(loop)}
function ground(){return canvas.getBoundingClientRect().height-82}
function burst(kind,count=8){if(!state)return;for(let i=0;i<count;i++)state.particles.push({kind,x:125+Math.random()*34,y:ground()-8-Math.random()*18,vx:(kind==='spark'?-80:-30)-Math.random()*130,vy:-35-Math.random()*110,life:.35+Math.random()*.35,max:.7,size:2+Math.random()*5})}
function jump(){if(!state||!state.running||state.paused)return;const p=state.player;if(p.jumpCount<2){p.vy=-(610+Math.min(active*4,55));p.slide=false;p.jumpCount++;burst(p.jumpCount===2?'spark':'dust',p.jumpCount===2?14:9);tone(p.jumpCount===2?520:340,p.jumpCount===2?920:610,.13,p.jumpCount===2?.055:.04,'triangle');if(p.jumpCount===2)toast('ดับเบิลจัมป์! ✨')}}
function slide(on=true){if(!state||!state.running)return;const p=state.player;if(on&&!p.slide){burst('slide',12);tone(190,70,.18,.035,'sawtooth')}p.slide=on;if(on&&p.y>0)p.vy+=180}
$('#jumpBtn').onpointerdown=e=>{e.preventDefault();jump()};$('#slideBtn').onpointerdown=e=>{e.preventDefault();slide(true)};$('#slideBtn').onpointerup=$('#slideBtn').onpointerleave=()=>slide(false);
addEventListener('keydown',e=>{if(['Space','ArrowUp'].includes(e.code)){e.preventDefault();jump()}if(['ArrowDown','KeyS'].includes(e.code)){e.preventDefault();slide(true)}if(e.code==='KeyP'||e.code==='Escape')pause()});addEventListener('keyup',e=>{if(['ArrowDown','KeyS'].includes(e.code))slide(false)});
$('#pauseBtn').onclick=pause;function pause(){if(!state||!state.running)return;state.paused=!state.paused;if(state.paused)overlay(`<h2>หยุดพัก</h2><p class="muted">พร้อมแล้วค่อยลุยต่อ</p><button class="btn primary" id="resume">วิ่งต่อ ▶</button><button class="btn" id="quit">กลับหน้าหลัก</button>`,()=>{$('#resume').onclick=()=>{hideOverlay();state.paused=false;last=performance.now()};$('#quit').onclick=()=>show('home')});else hideOverlay()}
function overlay(html,ready){$('#overlayPanel').innerHTML=html;$('#gameOverlay').classList.remove('hidden');ready?.()}function hideOverlay(){$('#gameOverlay').classList.add('hidden')}
function spawn(){const r=Math.random();let type=r<.52?'coin':r<.72?'rock':r<.91?'sign':'power';state.items.push({type,x:canvas.getBoundingClientRect().width+40,y:type==='coin'?(Math.random()<.5?55:125):0,hit:false})}
function loop(now){if(!state)return;const dt=Math.min((now-last)/1000,.034);last=now;if(state.running&&!state.paused)tick(dt);draw();raf=requestAnimationFrame(loop)}
function tick(dt){const s=state,p=s.player,wasAir=p.y>1;s.t+=dt;s.distance+=s.speed*dt/10;s.score+=Math.floor(dt*s.speed/9);s.speed+=dt*1.2;s.spawn-=dt;p.vy+=1550*dt;p.y=Math.max(0,p.y-p.vy*dt);if(p.y===0&&p.vy>0){p.vy=0;p.jumpCount=0;if(wasAir)burst('dust',13)}s.inv=Math.max(0,s.inv-dt);s.power=Math.max(0,s.power-dt);if(p.y===0&&Math.random()<dt*8)burst('dust',1);for(const q of s.particles){q.life-=dt;q.x+=q.vx*dt;q.y+=q.vy*dt;q.vy+=180*dt} s.particles=s.particles.filter(q=>q.life>0);if(s.spawn<=0){spawn();s.spawn=.55+Math.random()*.65-Math.min(active*.012,.2)}
 for(const o of s.items){o.x-=s.speed*dt;const pw=p.slide?64:46,ph=p.slide?32:72,py=ground()-p.y-ph,oh=o.type==='sign'?48:o.type==='rock'?50:30,oy=o.type==='sign'?ground()-112:ground()-oh-o.y;if(!o.hit&&o.x<110+pw&&o.x+42>110&&oy<py+ph&&oy+oh>py){o.hit=true;if(o.type==='coin'){s.coins++;s.score+=100;s.energy=Math.min(100,s.energy+12);playCoinSound()}else if(o.type==='power'){s.power=7;s.energy=100;s.score+=250;playSfx('power');toast('⚡ พลังปลาหลด! คุ้มกัน 7 วินาที')}else if(s.power<=0&&s.inv<=0){s.lives--;s.inv=1.5;s.energy=Math.max(0,s.energy-25);playSfx('hit');if(s.lives<=0)return finish(false)}}}s.items=s.items.filter(o=>o.x>-70&&!o.hit);if(s.energy>=100&&s.power<=0){s.power=7;s.energy=0;playSfx('power');toast('⚡ Energy เต็ม — เปิดโล่!')}if(s.distance>=s.target)gate();updateHud()}
function updateHud(){if(!state)return;$('#hearts').textContent='❤️'.repeat(state.lives)+'🖤'.repeat(3-state.lives);$('#coinHud').textContent=state.coins;$('#scoreHud').textContent=state.score;$('#energyFill').style.width=(state.power>0?100:state.energy)+'%';$('#stageHud').textContent=`${active+1}/20 • ${Math.min(100,Math.floor(state.distance/state.target*100))}%`}
function gate(){state.running=false;const q=QUESTIONS[active%QUESTIONS.length];overlay(`<div class="eyebrow">KNOWLEDGE GATE</div><h2>${q[0]}</h2><p class="muted">ตอบถูกเพื่อรับตรา Saket Passport</p><div class="answers">${q[1].map((a,i)=>`<button class="answer" data-a="${i}">${a}</button>`).join('')}</div>`,()=>document.querySelectorAll('.answer').forEach(b=>b.onclick=()=>{document.querySelectorAll('.answer').forEach(x=>x.disabled=true);const ok=+b.dataset.a===q[2];b.classList.add(ok?'good':'bad');if(ok){state.score+=500;setTimeout(()=>finish(true),650)}else{document.querySelector(`[data-a="${q[2]}"]`).classList.add('good');setTimeout(()=>{state.running=true;hideOverlay();last=performance.now()},950)}}))}
function finish(won){state.running=false;const stars=won?(state.lives===3?3:state.lives===2?2:1):0,total=state.score+(won?state.lives*200:0);if(won){const old=save.levels[active];save.levels[active]={stars:Math.max(stars,old?.stars||0),score:Math.max(total,old?.score||0)};save.unlocked=Math.min(20,Math.max(save.unlocked,active+2));save.coins+=state.coins}save.best=Math.max(save.best,total);save.scores.push({name:save.name,score:total,level:active+1,date:Date.now()});save.scores=save.scores.sort((a,b)=>b.score-a.score).slice(0,20);persist();overlay(`<div class="eyebrow">${won?'DISCOVERY COMPLETE':'TRY AGAIN'}</div><h2>${won?'ประทับตราสำเร็จ! 🎉':'หมดแรงแล้ว!'}</h2><p>${PLACES[active][0]} • ${PLACES[active][1]}</p><div class="result-grid"><div><b>${total}</b>คะแนน</div><div><b>${state.coins}</b>เหรียญ</div><div><b>${won?'★'.repeat(stars):'—'}</b>ดาว</div></div><button class="btn primary" id="again">${won&&active<19?'ด่านถัดไป ▶':'ลองอีกครั้ง'}</button><button class="btn" id="toMap">แผนที่ด่าน</button>`,()=>{$('#again').onclick=()=>start(won&&active<19?active+1:active);$('#toMap').onclick=()=>show('stages')})}
function drawFieldObstacle(o,oy){ctx.save();ctx.shadowColor='#1f160bb0';ctx.shadowBlur=10;ctx.shadowOffsetY=5;const floor=ground();if(o.type==='rock'){const x=o.x,y=floor-50;ctx.fillStyle='#74451f';ctx.strokeStyle='#3a210f';ctx.lineWidth=4;ctx.beginPath();ctx.roundRect(x-3,y+19,49,31,8);ctx.fill();ctx.stroke();ctx.fillStyle='#e6ad3d';ctx.beginPath();ctx.arc(x+20,y+25,22,0,7);ctx.fill();ctx.stroke();ctx.strokeStyle='#fff1a0';ctx.lineWidth=3;ctx.beginPath();ctx.arc(x+20,y+25,13,.2,5.4);ctx.stroke();ctx.strokeStyle='#9e671f';ctx.lineWidth=2;for(let i=-1;i<3;i++){ctx.beginPath();ctx.moveTo(x+4+i*10,y+9);ctx.lineTo(x+17+i*9,y+41);ctx.stroke()}ctx.fillStyle='#3a210f55';ctx.beginPath();ctx.ellipse(x+20,floor+2,28,5,0,0,7);ctx.fill()}else if(o.type==='sign'){const x=o.x,y=floor-108;ctx.strokeStyle='#382516';ctx.lineWidth=9;ctx.lineCap='butt';ctx.beginPath();ctx.moveTo(x+2,y);ctx.lineTo(x+2,floor);ctx.moveTo(x+43,y);ctx.lineTo(x+43,floor);ctx.stroke();ctx.strokeStyle='#d8a84e';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(x+2,y);ctx.lineTo(x+2,floor);ctx.moveTo(x+43,y);ctx.lineTo(x+43,floor);ctx.moveTo(x-4,y+5);ctx.lineTo(x+49,y+5);ctx.stroke();ctx.fillStyle='#f1c94c';ctx.strokeStyle='#604018';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(x+3,y+8);ctx.lineTo(x+43,y+8);ctx.lineTo(x+37,y+49);ctx.quadraticCurveTo(x+22,y+62,x+8,y+49);ctx.closePath();ctx.fill();ctx.stroke();ctx.strokeStyle='#fff0a0';ctx.lineWidth=2;for(let i=0;i<5;i++){ctx.beginPath();ctx.moveTo(x+9+i*7,y+14);ctx.lineTo(x+12+i*5,y+46);ctx.stroke()}ctx.fillStyle='#2e1b0d88';ctx.beginPath();ctx.ellipse(x+22,floor+2,31,5,0,0,7);ctx.fill()}else{ctx.shadowColor='#fff26b';ctx.shadowBlur=18;ctx.fillStyle='#fff7a0';ctx.beginPath();ctx.arc(o.x+19,oy+19,21,0,7);ctx.fill();ctx.font='30px serif';ctx.fillText('⚡',o.x+3,oy+31)}ctx.restore()}
function draw(){
 const w=canvas.getBoundingClientRect().width,h=canvas.getBoundingClientRect().height,g=ground();ctx.clearRect(0,0,w,h);
 if(fieldBackground.complete&&fieldBackground.naturalWidth){const dh=g+15,dw=fieldBackground.naturalWidth*(dh/fieldBackground.naturalHeight),travel=state.distance*1.7,start=Math.floor(travel/dw),off=-(travel%dw);for(let i=-1;i<Math.ceil(w/dw)+2;i++){const tile=start+i,x=off+i*dw;ctx.save();if(Math.abs(tile)%2===1){ctx.translate(x+dw,0);ctx.scale(-1,1);ctx.drawImage(fieldBackground,0,0,dw,dh)}else ctx.drawImage(fieldBackground,x,0,dw,dh);ctx.restore()}}else{const sky=ctx.createLinearGradient(0,0,0,g);sky.addColorStop(0,'#55cbea');sky.addColorStop(1,'#e8d66f');ctx.fillStyle=sky;ctx.fillRect(0,0,w,g)}
 const haze=ctx.createLinearGradient(0,g-90,0,g+10);haze.addColorStop(0,'#f7db6955');haze.addColorStop(1,'#416d2600');ctx.fillStyle=haze;ctx.fillRect(0,g-90,w,100);
 const road=ctx.createLinearGradient(0,g,0,h);road.addColorStop(0,'#b77a39');road.addColorStop(.35,'#8b552d');road.addColorStop(1,'#50321f');ctx.fillStyle=road;ctx.fillRect(0,g,w,h-g);ctx.fillStyle='#e0b75d';ctx.fillRect(0,g,w,8);ctx.fillStyle='#597f29';ctx.fillRect(0,g-7,w,9);
 ctx.globalAlpha=.24;ctx.strokeStyle='#f6d48a';ctx.lineWidth=2;for(let i=0;i<8;i++){const y=g+17+i*14,shift=(state.distance*(8+i*1.3))%90;ctx.setLineDash([38,52]);ctx.lineDashOffset=-shift;ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}ctx.setLineDash([]);ctx.globalAlpha=1;
 for(let x=-30-(state.distance*9%55);x<w;x+=55){ctx.fillStyle='#c9984e';ctx.beginPath();ctx.ellipse(x,g+35,15,4,0,0,7);ctx.fill()}
 for(const q of state.particles){const a=Math.max(0,q.life/q.max);ctx.globalAlpha=a;ctx.fillStyle=q.kind==='spark'?'#fff07b':q.kind==='slide'?'#ffe2a1':'#dfb86f';ctx.beginPath();if(q.kind==='slide')ctx.ellipse(q.x,q.y,q.size*2,q.size*.55,-.25,0,7);else ctx.arc(q.x,q.y,q.size,0,7);ctx.fill()}ctx.globalAlpha=1;
 const p=state.player;ctx.fillStyle='#24160d55';ctx.beginPath();ctx.ellipse(140,g+5,Math.max(18,48-p.y*.08),7,0,0,7);ctx.fill();if(p.slide){ctx.strokeStyle='#fff3bb88';ctx.lineWidth=3;for(let i=0;i<5;i++){ctx.beginPath();ctx.moveTo(30-i*14,g-24-i*7);ctx.lineTo(95-i*5,g-24-i*7);ctx.stroke()}}
 for(const o of state.items){const oy=o.type==='sign'?g-112:o.type==='rock'?g-50:g-30-o.y;if(o.type==='coin'&&coinImage.complete){ctx.save();ctx.translate(o.x+20,oy+20);const pulse=1+Math.sin(state.t*7+o.x)*.07;ctx.scale(pulse,pulse);ctx.shadowColor='#ffdd45';ctx.shadowBlur=13;ctx.beginPath();ctx.arc(0,0,21,0,7);ctx.clip();ctx.drawImage(coinImage,-21,-21,42,42);ctx.restore();ctx.strokeStyle='#fff2a2';ctx.lineWidth=2;ctx.beginPath();ctx.arc(o.x+20,oy+20,21,0,7);ctx.stroke()}else drawFieldObstacle(o,oy)}
 const py=g-p.y-(p.slide?32:72);let frame;if(p.slide)frame=slideFrames[Math.floor(state.t*10)%slideFrames.length];else if(p.y>1){const ji=p.vy<-300?0:p.vy<-50?1:p.vy<200?2:p.vy<450?3:4;frame=jumpFrames[ji]}else frame=runFrames[Math.floor(state.t*(7+state.speed/100))%runFrames.length];ctx.globalAlpha=state.inv>0&&Math.floor(state.inv*12)%2?0.3:1;ctx.save();ctx.translate(135,py+(p.slide?34:44));const cw=p.slide?112:100,ch=p.slide?76:100;ctx.shadowColor='#23150d55';ctx.shadowBlur=9;ctx.shadowOffsetY=6;if(frame?.complete)ctx.drawImage(frame,-cw/2,-ch/2,cw,ch);else{ctx.font='64px serif';ctx.fillText('🐟',-30,22)}ctx.restore();ctx.globalAlpha=1;
 if(state.power>0){ctx.strokeStyle='#ffe866';ctx.lineWidth=5;ctx.shadowColor='#fff36b';ctx.shadowBlur=15;ctx.beginPath();ctx.arc(140,py+30,58+Math.sin(state.t*8)*3,0,7);ctx.stroke();ctx.shadowBlur=0}
}
// Optional Supabase: set window.LOHD_SUPABASE={url,key} before this module to mirror scores.
async function syncCloud(){const c=window.LOHD_SUPABASE;if(!c?.url||!c?.key)return;try{await fetch(`${c.url}/rest/v1/leaderboard`,{method:'POST',headers:{apikey:c.key,Authorization:`Bearer ${c.key}`,'Content-Type':'application/json',Prefer:'resolution=merge-duplicates'},body:JSON.stringify({name:save.name,score:save.best,level:save.unlocked})})}catch(e){console.info('Cloud sync unavailable; local save remains active.')}}
updateHome();renderStages();show('home');

